services:
    d120de.banner.listener:
        class: d120de\banner\event\main_listener
        arguments:
            - @config
            - @controller.helper
            - @template
        tags:
            - { name: event.listener }
